info:
  # Blog Information
  title:        "Amit Bijlani"
  subtitle:     "iOS Developer, Speaker, Writer, and Dreamer"
  cover_image:  short-north-columbus-oh.jpg
  cover_image_caption: ""
  about_image:  goodale-park-columbus-oh.jpg
  about_image_caption: ""
  logo:         logo.png

  # Social links
  # facebook:     sendtoinc
  twitter:      paradoxed
  github:       abijlani

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  paradoxed

  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id: 'UA-63929907-1'

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         true
    reddit:     true

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

# Root URL where the site will be published
url:         http://amitbijlani.com/swiftbites

# host 0.0.0.0 allows us to access site via sapphire.local or localhost or 127.0.0.1
host: 0.0.0.0

paginate:             10

# safe mode must be disabled to use jekyll-assets.
safe:               false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
